services:
  web-app:
    build:
      context: ./service
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
  database:
    image: postgres:14.6-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build:
      context: ./service
    hostname: worker
    command: celery -A app worker -l info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

  flower:
    build:
      context: ./service
    hostname: flower
    entrypoint: celery
    command: -A app flower
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

